// Flat config generated by @nuxt/eslint (see nuxt.config.ts).
import withNuxt from "./.nuxt/eslint.config.mjs";

export default withNuxt({
  rules: {
    // Align with Prettier, which self-closes void elements (e.g. <img />). The Vue preset
    // defaults `void` to "never", causing an eslint↔prettier ping-pong on void tags.
    "vue/html-self-closing": [
      "warn",
      {
        html: { void: "always", normal: "always", component: "always" },
        svg: "always",
        math: "always",
      },
    ],
  },
});
