// Flat config generated by @nuxt/eslint (see nuxt.config.ts).
import withNuxt from "./.nuxt/eslint.config.mjs";

export default withNuxt(
  {
    rules: {
      // Align with Prettier, which self-closes void elements (e.g. <img />). The Vue preset
      // defaults `void` to "never", causing an eslint↔prettier ping-pong on void tags.
      "vue/html-self-closing": [
        "warn",
        {
          html: { void: "always", normal: "always", component: "always" },
          svg: "always",
          math: "always",
        },
      ],
    },
  },
  {
    // Design-system guardrail (docs/08): app code goes through <AppButton>/<IconButton>/<AppBadge>
    // + the icons registry, never raw <UButton>/<UBadge>/i-lucide-* strings. Allowlist below =
    // wrappers/registry/styleguide.
    files: ["app/**/*.vue", "app/**/*.ts"],
    ignores: [
      "app/components/AppButton.vue",
      "app/components/IconButton.vue",
      "app/components/AppBadge.vue",
      "app/components/StyleguideGallery.vue",
      "app/pages/styleguide.vue",
      "app/utils/icons.ts",
      "app/**/*.spec.ts",
    ],
    rules: {
      "vue/no-restricted-syntax": [
        "error",
        {
          selector: "VElement[rawName='UButton']",
          message:
            "改用 <AppButton> / <IconButton>,勿直接用 <UButton>(見 components/AppButton.vue)。",
        },
        {
          // UColorModeButton is a compound wrapper (not UButton), so the rule above misses it; it
          // slipped past the guardrail as a raw icon button. Route the theme switch through
          // <ColorModeToggle> (→ IconButton) so it inherits the design system too.
          selector: "VElement[rawName='UColorModeButton']",
          message: "改用 <ColorModeToggle>(走 IconButton 設計系統),勿直接用 <UColorModeButton>。",
        },
        {
          selector: "VElement[rawName='UBadge']",
          message: "改用 <AppBadge>,勿直接用 <UBadge>(見 components/AppBadge.vue)。",
        },
        {
          selector:
            "VElement[rawName='AppBadge'] VAttribute[directive=false][key.name=/^(color|variant)$/]",
          message: "AppBadge 不吃 color/variant,改用 intent(見 utils/badge-intents.ts)。",
        },
        {
          selector:
            "VElement[rawName='AppBadge'] VAttribute[directive=true][key.argument.name=/^(color|variant)$/]",
          message: "AppBadge 不吃 color/variant,改用 intent(見 utils/badge-intents.ts)。",
        },
        {
          selector: 'VLiteral[value=/^"?i-lucide-/]',
          message: "改用 icons 登記表(icons.*),勿在模板寫 i-lucide-* 字串(見 utils/icons.ts)。",
        },
        {
          selector: "Literal[value=/^i-lucide-/]",
          message: "改用 icons 登記表(icons.*),勿寫 i-lucide-* 字串(見 utils/icons.ts)。",
        },
      ],
      "no-restricted-syntax": [
        "error",
        {
          selector: "Literal[value=/^i-lucide-/]",
          message: "改用 icons 登記表(icons.*),勿寫 i-lucide-* 字串(見 utils/icons.ts)。",
        },
      ],
    },
  },
);
