// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2025-07-15",
  devtools: { enabled: true },
  telemetry: false,
  modules: [
    "@nuxt/ui",
    "@nuxtjs/mdc",
    "@nuxt/image",
    "@nuxtjs/seo",
    "@nuxtjs/i18n",
    "@pinia/nuxt",
    "@vueuse/motion/nuxt",
    "@nuxt/eslint",
  ],
  css: ["~/assets/css/main.css", "katex/dist/katex.min.css"],
  // Self-hosted GenWanMin2 TW @font-face chunks (headings serif); generated by tools/font-subset.
  app: { head: { link: [{ rel: "stylesheet", href: "/fonts/genwanmin/result.css" }] } },
  // Runtime MDC (<MDC :value>) renders DB-sourced Markdown; add math support so `$…$`
  // (used heavily by DSA/math papers) renders via KaTeX. English papers need only base prose.
  mdc: {
    remarkPlugins: { "remark-math": {} },
    rehypePlugins: { "rehype-katex": {} },
  },
  // Public runtime config; override per-env via NUXT_PUBLIC_* (see docs/01-architecture.md env layers).
  runtimeConfig: {
    public: {
      apiBaseUrl: process.env.NUXT_PUBLIC_API_BASE_URL || "http://localhost:8088/api/v1",
    },
  },
  // CF Pages hybrid: content pages prerender at build, dynamic (API-driven) pages render client-side.
  nitro: { preset: "cloudflare-pages" },
  routeRules: {
    "/": { prerender: true },
    // API-driven pages render client-side (edge can't reach the origin DB at build time).
    // SEO prerender of question/answer pages comes with the content pipeline (Phase 2).
    "/schedules": { ssr: false },
    "/admissions": { ssr: false },
    "/questions/**": { ssr: false },
  },
  // All icons are Lucide (Nuxt UI v4 defaults; the app adds none). Client-bundle them so they load
  // locally instead of from the Iconify CDN at runtime (the default "remote" mode). Nuxt UI pulls
  // its icons via app config, which `scan` can't see, so the full default set is listed explicitly.
  icon: {
    clientBundle: {
      scan: true,
      icons: [
        "lucide:arrow-left",
        "lucide:arrow-right",
        "lucide:arrow-up-right",
        "lucide:check",
        "lucide:chevron-down",
        "lucide:chevron-left",
        "lucide:chevron-right",
        "lucide:chevron-up",
        "lucide:chevrons-left",
        "lucide:chevrons-right",
        "lucide:circle-alert",
        "lucide:circle-check",
        "lucide:circle-x",
        "lucide:copy",
        "lucide:copy-check",
        "lucide:ellipsis",
        "lucide:eye",
        "lucide:eye-off",
        "lucide:file",
        "lucide:folder",
        "lucide:info",
        "lucide:lightbulb",
        "lucide:loader-circle",
        "lucide:menu",
        "lucide:minus",
        "lucide:monitor",
        "lucide:moon",
        "lucide:panel-left-close",
        "lucide:panel-left-open",
        "lucide:plus",
        "lucide:rotate-ccw",
        "lucide:search",
        "lucide:square",
        "lucide:sun",
        "lucide:triangle-alert",
        "lucide:upload",
        "lucide:x",
      ],
    },
  },
  // Formatting is handled by Prettier.
  eslint: { config: { stylistic: false } },
  // url is env-driven (NUXT_PUBLIC_SITE_URL) so prod/staging/preview each set their own; no real domain yet.
  site: { name: "ProGrads", url: process.env.NUXT_PUBLIC_SITE_URL || "https://app.example.com" },
  // OG image generation needs a native renderer; enable later when needed.
  ogImage: { enabled: false },
  i18n: {
    defaultLocale: "zh-TW",
    strategy: "no_prefix",
    locales: [{ code: "zh-TW", language: "zh-TW", name: "繁體中文" }],
  },
  vite: {
    optimizeDeps: { include: ["@tanstack/vue-query", "@unhead/schema-org/vue"] },
  },
});
