// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2025-07-15",
  devtools: { enabled: true },
  telemetry: false,
  modules: [
    "@nuxt/ui",
    "@nuxtjs/mdc",
    "@nuxt/image",
    "@nuxtjs/seo",
    "@nuxtjs/i18n",
    "@pinia/nuxt",
    "@vueuse/motion/nuxt",
    "@nuxt/eslint",
  ],
  // KaTeX CSS is scoped to questions/[externalId].vue (the only page rendering math via MDC),
  // so it code-splits with that route instead of blocking every page (incl. prerendered /).
  css: ["~/assets/css/main.css"],
  // Self-hosted GenWanMin2 TW @font-face chunks (headings serif); generated by tools/font-subset.
  // Loaded non-render-blocking: preload the 276KB sheet, then promote to a stylesheet on load so
  // first paint isn't gated on it. Serif headings show a brief fallback then swap (FOUT), governed
  // by the sheet's own font-display; <noscript> keeps it working with JS disabled.
  app: {
    head: {
      // Brand icons: vector monogram (public/logo.svg, blackboard-green, dark-mode→cream),
      // transparent. SVG first (modern browsers prefer it); .ico + PNGs are fallbacks.
      link: [
        { rel: "icon", type: "image/svg+xml", href: "/favicon.svg" },
        { rel: "icon", href: "/favicon.ico", sizes: "any" },
        { rel: "icon", type: "image/png", sizes: "32x32", href: "/favicon-32x32.png" },
        { rel: "icon", type: "image/png", sizes: "16x16", href: "/favicon-16x16.png" },
        { rel: "apple-touch-icon", sizes: "180x180", href: "/apple-touch-icon.png" },
        { rel: "manifest", href: "/site.webmanifest" },
        {
          rel: "preload",
          as: "style",
          href: "/fonts/genwanmin/result.css",
          onload: "this.onload=null;this.rel='stylesheet'",
        },
      ],
      meta: [{ name: "theme-color", content: "#243b30" }],
      noscript: [{ innerHTML: '<link rel="stylesheet" href="/fonts/genwanmin/result.css">' }],
    },
  },
  // Runtime MDC (<MDC :value>) renders DB-sourced Markdown; add math support so `$…$`
  // (used heavily by DSA/math papers) renders via KaTeX. English papers need only base prose.
  mdc: {
    remarkPlugins: { "remark-math": {} },
    // KaTeX lacks \textsc (small caps); CLRS-style papers use it for procedure names
    // (e.g. \textsc{Random}). Map it to \text so the name renders instead of red error text.
    rehypePlugins: { "rehype-katex": { macros: { "\\textsc": "\\text{#1}" } } },
    // Shiki bundles only the grammars listed here; others fall back to plain text. Cover our
    // CS / info-mgmt paper languages. (Unlabelled blocks need no entry; there is no "plaintext" id.)
    // One theme = a single unified look (colours + font) for every code block; only the blackboard
    // swaps the block background (components.css) so its dark code fits the board.
    highlight: {
      theme: "github-dark",
      langs: ["c", "cpp", "java", "python", "javascript", "sql", "asm", "bash"],
    },
  },
  // Public runtime config; override per-env via NUXT_PUBLIC_* (see docs/01-architecture.md env layers).
  runtimeConfig: {
    public: {
      apiBaseUrl: process.env.NUXT_PUBLIC_API_BASE_URL || "http://localhost:8088/api/v1",
    },
  },
  // CF Pages hybrid: content pages prerender at build, dynamic (API-driven) pages render client-side.
  // Only build the Cloudflare worker bundle for production builds — in dev it adds ~15s to every
  // startup for no benefit (dev uses Nitro's own dev server), so fall back to the default preset.
  nitro: { preset: process.env.NODE_ENV === "production" ? "cloudflare-pages" : undefined },
  routeRules: {
    "/": { prerender: true },
    // API-driven pages render client-side (edge can't reach the origin DB at build time).
    // SEO prerender of question/answer pages comes with the content pipeline (Phase 2).
    "/schedules": { ssr: false },
    "/admissions": { ssr: false },
    "/faculty": { ssr: false },
    "/questions/**": { ssr: false },
  },
  // All icons are Lucide (Nuxt UI v4 defaults; the app adds none). Client-bundle them so they load
  // locally instead of from the Iconify CDN at runtime (the default "remote" mode). Nuxt UI pulls
  // its icons via app config, which `scan` can't see, so the full default set is listed explicitly.
  icon: {
    clientBundle: {
      scan: true,
      icons: [
        "lucide:arrow-left",
        "lucide:arrow-right",
        "lucide:arrow-up-right",
        "lucide:check",
        "lucide:chevron-down",
        "lucide:chevron-left",
        "lucide:chevron-right",
        "lucide:chevron-up",
        "lucide:chevrons-left",
        "lucide:chevrons-right",
        "lucide:circle-alert",
        "lucide:circle-check",
        "lucide:circle-x",
        "lucide:copy",
        "lucide:copy-check",
        "lucide:ellipsis",
        "lucide:eye",
        "lucide:eye-off",
        "lucide:file",
        "lucide:folder",
        "lucide:info",
        "lucide:lightbulb",
        "lucide:loader-circle",
        "lucide:menu",
        "lucide:minus",
        "lucide:monitor",
        "lucide:moon",
        "lucide:panel-left-close",
        "lucide:panel-left-open",
        "lucide:plus",
        "lucide:rotate-ccw",
        "lucide:search",
        "lucide:square",
        "lucide:sun",
        "lucide:triangle-alert",
        "lucide:upload",
        "lucide:x",
      ],
    },
  },
  // Formatting is handled by Prettier.
  eslint: { config: { stylistic: false } },
  // url is env-driven (NUXT_PUBLIC_SITE_URL) so prod/staging/preview each set their own; no real domain yet.
  site: { name: "ProGrads", url: process.env.NUXT_PUBLIC_SITE_URL || "https://app.example.com" },
  // OG image generation needs a native renderer; enable later when needed.
  ogImage: { enabled: false },
  i18n: {
    defaultLocale: "zh-TW",
    strategy: "no_prefix",
    locales: [{ code: "zh-TW", language: "zh-TW", name: "繁體中文" }],
  },
  vite: {
    // Pre-bundle deps Vite would otherwise discover mid-session (MDC math plugins, vue-query,
    // schema-org, and the Schedule-X calendar + its temporal polyfill, which only load on
    // /schedules) so dev doesn't trigger a re-optimize page reload.
    optimizeDeps: {
      include: [
        "@schedule-x/calendar",
        "@schedule-x/vue",
        "@tanstack/vue-query",
        "@unhead/schema-org/vue",
        "rehype-katex",
        "remark-math",
        "temporal-polyfill/global",
      ],
    },
  },
});
