import type { PrismaClient } from "../../generated/client/client.ts";

// Subject-scoped controlled vocabulary for exam knowledge points. See docs/02-data-model.md and
// docs/09-roadmap.md §考科趨勢. Flat list, one row per L2 leaf — the offline parser
// (seed-refs.ts readKnowledgePoints) pairs each entry's `subject` field with the `slug` field
// right after it, so keep that order. Only `slug` (the leaf) may be tagged on a question;
// `groupSlug`/`groupName` are L1 browsing groups, never tagged directly.
//
// Granularity comes from the actual exam corpus per subject, not an imposed syllabus. `name`
// uses English/original terminology; `aliases` holds every other form (Chinese, abbreviations,
// variants) — unstructured, not a statistics key.
//
// Empty pool = no taxonomy built for that subject yet; add entries via PR once ready.
export interface KnowledgePointSeed {
  subject: string; // Subject.slug (taxonomy.seed.ts)
  groupSlug: string;
  groupName: string;
  slug: string;
  name: string;
  aliases?: string[];
}

// Derived from the collected exam corpus per subject — see git history for each subject's
// extraction/clustering. Draft; re-cluster as more papers are added.
const KNOWLEDGE_POINTS: KnowledgePointSeed[] = [
  // ---------- ds (資料結構) ----------
  {
    subject: "ds",
    groupSlug: "linear-structures",
    groupName: "Linear structures",
    slug: "stack",
    name: "Stack",
    aliases: ["堆疊", "LIFO", "堆疊求值", "後綴表示法", "抽象資料型別", "運算子優先序", "括號"],
  },
  {
    subject: "ds",
    groupSlug: "linear-structures",
    groupName: "Linear structures",
    slug: "queue",
    name: "Queue",
    aliases: ["佇列", "FIFO", "環形陣列", "佇列與堆疊", "雙堆疊實作佇列", "輸出序列合法性"],
  },
  {
    subject: "ds",
    groupSlug: "linear-structures",
    groupName: "Linear structures",
    slug: "linked-list",
    name: "Linked list",
    aliases: ["鏈結串列", "單向串列", "尾指標"],
  },
  {
    subject: "ds",
    groupSlug: "linear-structures",
    groupName: "Linear structures",
    slug: "dynamic-array",
    name: "Dynamic array",
    aliases: ["動態陣列", "攤還分析", "攤銷分析", "倍增策略", "收縮門檻"],
  },
  {
    subject: "ds",
    groupSlug: "trees",
    groupName: "Trees",
    slug: "binary-tree",
    name: "Binary tree",
    aliases: [
      "二元樹",
      "中序遍歷",
      "後序遍歷",
      "層序遍歷",
      "運算式樹",
      "表達式樹",
      "二元樹重建",
      "前綴中綴後綴",
      "陣列表示",
      "BFS",
      "後序走訪",
      "中序/後序走訪",
      "遍歷唯一性",
    ],
  },
  {
    subject: "ds",
    groupSlug: "trees",
    groupName: "Trees",
    slug: "binary-search-tree",
    name: "Binary search tree",
    aliases: [
      "二元搜尋樹",
      "陣列實作二元搜尋樹",
      "中序後繼",
      "第k大元素",
      "順序統計量",
      "樹的索引",
      "搜尋路徑",
      "Join操作",
    ],
  },
  {
    subject: "ds",
    groupSlug: "trees",
    groupName: "Trees",
    slug: "avl-tree",
    name: "AVL tree",
    aliases: ["AVL樹", "平衡因子"],
  },
  {
    subject: "ds",
    groupSlug: "trees",
    groupName: "Trees",
    slug: "red-black-tree",
    name: "Red-black tree",
    aliases: ["紅黑樹", "黑高", "樹高上界"],
  },
  {
    subject: "ds",
    groupSlug: "trees",
    groupName: "Trees",
    slug: "b-plus-tree",
    name: "B+ tree",
    aliases: ["B+樹", "節點路由", "鍵值範圍", "葉節點資料"],
  },
  {
    subject: "ds",
    groupSlug: "heap-and-priority-queue",
    groupName: "Heap and priority queue",
    slug: "heap",
    name: "Heap",
    aliases: ["陣列實作最大堆積", "堆積索引", "最大堆積性質", "合併"],
  },
  {
    subject: "ds",
    groupSlug: "heap-and-priority-queue",
    groupName: "Heap and priority queue",
    slug: "priority-queue",
    name: "Priority queue",
    aliases: ["優先佇列", "堆積應用", "串流中位數", "事件驅動模擬"],
  },
  {
    subject: "ds",
    groupSlug: "hashing",
    groupName: "Hashing",
    slug: "hash-table",
    name: "Hash table",
    aliases: [
      "雜湊表",
      "雜湊",
      "雜湊函數設計",
      "碰撞",
      "碰撞處理",
      "線性探測",
      "雙重雜湊",
      "通用雜湊族",
      "碰撞期望值",
      "最壞情況分析",
      "十六進位",
      "模除",
    ],
  },
  {
    subject: "ds",
    groupSlug: "linear-structures",
    groupName: "Linear structures",
    slug: "sorted-list-operations",
    name: "Sorted list operations (merge-based set intersection)",
    aliases: ["排序串列", "集合交集"],
  },

  // ---------- algo (演算法) ----------
  {
    subject: "algo",
    groupSlug: "complexity-analysis",
    groupName: "Complexity analysis",
    slug: "asymptotic-notation",
    name: "Asymptotic notation",
    aliases: ["漸進記號", "大O與Ω", "漸進成長率", "複雜度分析", "時間複雜度", "空間複雜度"],
  },
  {
    subject: "algo",
    groupSlug: "complexity-analysis",
    groupName: "Complexity analysis",
    slug: "recurrence-relations",
    name: "Recurrence relations",
    aliases: [
      "遞迴關係",
      "遞迴關係式",
      "遞迴式",
      "遞迴式求解",
      "遞迴複雜度",
      "遞迴公式",
      "遞迴時間複雜度",
    ],
  },
  {
    subject: "algo",
    groupSlug: "complexity-analysis",
    groupName: "Complexity analysis",
    slug: "master-theorem",
    name: "Master theorem",
    aliases: ["主定理"],
  },
  {
    subject: "algo",
    groupSlug: "complexity-analysis",
    groupName: "Complexity analysis",
    slug: "akra-bazzi-theorem",
    name: "Akra-Bazzi theorem",
    aliases: ["Akra-Bazzi定理"],
  },
  {
    subject: "algo",
    groupSlug: "complexity-analysis",
    groupName: "Complexity analysis",
    slug: "amortized-analysis",
    name: "Amortized analysis",
    aliases: [
      "攤還分析",
      "攤銷分析",
      "攤還成本",
      "勢能法",
      "二進位計數器",
      "動態表格",
      "動態陣列",
      "記憶體管理",
      "倍增策略",
      "雙堆疊佇列",
    ],
  },
  {
    subject: "algo",
    groupSlug: "divide-and-conquer",
    groupName: "Divide and conquer",
    slug: "divide-and-conquer-technique",
    name: "Divide and conquer",
    aliases: ["分治法", "演算法範式"],
  },
  {
    subject: "algo",
    groupSlug: "divide-and-conquer",
    groupName: "Divide and conquer",
    slug: "matrix-multiplication",
    name: "Matrix multiplication",
    aliases: ["矩陣乘法"],
  },
  {
    subject: "algo",
    groupSlug: "divide-and-conquer",
    groupName: "Divide and conquer",
    slug: "fast-fourier-transform",
    name: "Fast Fourier transform",
    aliases: ["快速傅立葉轉換", "單位根"],
  },
  {
    subject: "algo",
    groupSlug: "sorting",
    groupName: "Sorting",
    slug: "quicksort",
    name: "Quicksort",
    aliases: ["快速排序", "樞紐選擇", "隨機化演算法", "最壞情況"],
  },
  {
    subject: "algo",
    groupSlug: "sorting",
    groupName: "Sorting",
    slug: "merge-sort",
    name: "Merge sort",
    aliases: ["合併排序", "多路合併", "外部排序", "最小堆積", "鏈結串列合併"],
  },
  {
    subject: "algo",
    groupSlug: "sorting",
    groupName: "Sorting",
    slug: "bubble-sort",
    name: "Bubble sort",
    aliases: ["氣泡排序", "逐趟過程", "相鄰交換"],
  },
  {
    subject: "algo",
    groupSlug: "sorting",
    groupName: "Sorting",
    slug: "selection-sort",
    name: "Selection sort",
    aliases: ["選擇排序"],
  },
  {
    subject: "algo",
    groupSlug: "sorting",
    groupName: "Sorting",
    slug: "non-comparison-sorting",
    name: "Non-comparison sorting",
    aliases: ["計數排序", "基數排序", "桶排序", "非比較排序", "期望線性時間", "均勻分布"],
  },
  {
    subject: "algo",
    groupSlug: "sorting",
    groupName: "Sorting",
    slug: "sorting-analysis",
    name: "Sorting algorithm analysis",
    aliases: [
      "排序演算法",
      "排序",
      "排序結果",
      "排序唯一性",
      "最壞情況",
      "最差情況分析",
      "平均情況",
    ],
  },
  {
    subject: "algo",
    groupSlug: "selection-and-order-statistics",
    groupName: "Selection and order statistics",
    slug: "selection-algorithm",
    name: "Selection algorithm",
    aliases: ["選擇問題", "中位數", "中位數的中位數", "最壞線性時間"],
  },
  {
    subject: "algo",
    groupSlug: "graph-traversal",
    groupName: "Graph traversal",
    slug: "graph-traversal-dfs-bfs",
    name: "Graph traversal (DFS/BFS)",
    aliases: [
      "DFS",
      "BFS",
      "深度優先搜尋",
      "廣度優先搜尋",
      "圖走訪",
      "環偵測",
      "回邊",
      "圖的連通分量",
      "佇列",
      "回溯法",
    ],
  },
  {
    subject: "algo",
    groupSlug: "graph-traversal",
    groupName: "Graph traversal",
    slug: "topological-sort",
    name: "Topological sort",
    aliases: ["拓撲排序", "拓樸排序", "有向無環圖", "DAG排程", "關鍵路徑"],
  },
  {
    subject: "algo",
    groupSlug: "shortest-path",
    groupName: "Shortest path",
    slug: "shortest-path-general",
    name: "Shortest path (general)",
    aliases: [
      "最短路徑",
      "單源最短路徑",
      "負權",
      "負權邊",
      "瓶頸路徑",
      "最短路徑距離",
      "Fibonacci heap",
    ],
  },
  {
    subject: "algo",
    groupSlug: "shortest-path",
    groupName: "Shortest path",
    slug: "dijkstra-algorithm",
    name: "Dijkstra's algorithm",
    aliases: ["Dijkstra"],
  },
  {
    subject: "algo",
    groupSlug: "shortest-path",
    groupName: "Shortest path",
    slug: "bellman-ford-algorithm",
    name: "Bellman-Ford algorithm",
    aliases: ["Bellman-Ford"],
  },
  {
    subject: "algo",
    groupSlug: "shortest-path",
    groupName: "Shortest path",
    slug: "floyd-warshall-algorithm",
    name: "Floyd-Warshall algorithm",
    aliases: ["Floyd-Warshall"],
  },
  {
    subject: "algo",
    groupSlug: "minimum-spanning-tree",
    groupName: "Minimum spanning tree",
    slug: "minimum-spanning-tree-general",
    name: "Minimum spanning tree (general)",
    aliases: ["最小生成樹", "生成樹", "環性質", "割性質", "安全邊", "對稱差", "擬陣"],
  },
  {
    subject: "algo",
    groupSlug: "minimum-spanning-tree",
    groupName: "Minimum spanning tree",
    slug: "prim-algorithm",
    name: "Prim's algorithm",
    aliases: ["Prim", "Prim演算法", "貪婪成長"],
  },
  {
    subject: "algo",
    groupSlug: "minimum-spanning-tree",
    groupName: "Minimum spanning tree",
    slug: "kruskal-algorithm",
    name: "Kruskal's algorithm",
    aliases: ["Kruskal", "邊排序", "割邊"],
  },
  {
    subject: "algo",
    groupSlug: "network-flow",
    groupName: "Network flow",
    slug: "max-flow-min-cut",
    name: "Max-flow min-cut",
    aliases: ["最大流", "最小割", "Ford-Fulkerson", "st網路", "網路流建模", "平面圖對偶"],
  },
  {
    subject: "algo",
    groupSlug: "network-flow",
    groupName: "Network flow",
    slug: "bipartite-matching",
    name: "Bipartite matching",
    aliases: ["二分圖匹配", "二分匹配", "最大匹配", "完美匹配", "指派問題"],
  },
  {
    subject: "algo",
    groupSlug: "string-algorithms",
    groupName: "String algorithms",
    slug: "kmp-algorithm",
    name: "KMP algorithm",
    aliases: ["KMP演算法", "KMP", "前綴函數", "失敗函數", "字串比對", "字串比對自動機"],
  },
  {
    subject: "algo",
    groupSlug: "string-algorithms",
    groupName: "String algorithms",
    slug: "rabin-karp-algorithm",
    name: "Rabin-Karp algorithm",
    aliases: ["Rabin-Karp", "滾動雜湊"],
  },
  {
    subject: "algo",
    groupSlug: "string-algorithms",
    groupName: "String algorithms",
    slug: "huffman-coding",
    name: "Huffman coding",
    aliases: ["霍夫曼編碼", "前綴碼", "編碼長度", "最佳性證明"],
  },
  {
    subject: "algo",
    groupSlug: "dynamic-programming",
    groupName: "Dynamic programming",
    slug: "dynamic-programming-general",
    name: "Dynamic programming (general)",
    aliases: ["動態規劃", "最佳子結構", "重疊子問題", "次佳解"],
  },
  {
    subject: "algo",
    groupSlug: "dynamic-programming",
    groupName: "Dynamic programming",
    slug: "knapsack-problem",
    name: "Knapsack problem",
    aliases: ["背包問題", "0/1背包", "無限背包"],
  },
  {
    subject: "algo",
    groupSlug: "dynamic-programming",
    groupName: "Dynamic programming",
    slug: "longest-common-subsequence",
    name: "Longest common subsequence",
    aliases: ["最長共同子序列", "LCS", "全域比對", "序列比對", "計數DP"],
  },
  {
    subject: "algo",
    groupSlug: "dynamic-programming",
    groupName: "Dynamic programming",
    slug: "matrix-chain-multiplication",
    name: "Matrix chain multiplication",
    aliases: ["矩陣鏈乘積", "子問題計數", "組合計數"],
  },
  {
    subject: "algo",
    groupSlug: "dynamic-programming",
    groupName: "Dynamic programming",
    slug: "tree-dp",
    name: "Tree DP",
    aliases: ["樹形DP", "樹DP", "換根法", "樹的直徑", "由上而下"],
  },
  {
    subject: "algo",
    groupSlug: "dynamic-programming",
    groupName: "Dynamic programming",
    slug: "interval-dp",
    name: "Interval DP",
    aliases: ["區間分割", "最小化最大值", "區間長度", "填表順序"],
  },
  {
    subject: "algo",
    groupSlug: "dynamic-programming",
    groupName: "Dynamic programming",
    slug: "grid-dp",
    name: "Grid DP",
    aliases: ["網格DP", "網格路徑", "snake sequence", "路徑回溯"],
  },
  {
    subject: "algo",
    groupSlug: "computational-complexity",
    groupName: "Computational complexity",
    slug: "np-completeness",
    name: "NP-completeness",
    aliases: [
      "NP",
      "NP-hard",
      "NP-Complete",
      "NP-complete",
      "NP-complete證明",
      "NP完全",
      "NP困難",
      "NP完備",
      "多項式歸約",
      "多項式時間歸約",
      "複雜度類",
      "P與NP",
      "停機問題",
      "子集和",
      "子集合和",
    ],
  },
  {
    subject: "algo",
    groupSlug: "computational-complexity",
    groupName: "Computational complexity",
    slug: "approximation-algorithms",
    name: "Approximation algorithms",
    aliases: ["近似演算法", "近似比", "FPTAS", "頂點覆蓋", "最小加權頂點覆蓋", "整數線性規劃"],
  },
  {
    subject: "algo",
    groupSlug: "computational-complexity",
    groupName: "Computational complexity",
    slug: "integer-linear-programming",
    name: "Integer/linear programming relaxation",
    aliases: ["0-1整數規劃", "LP鬆弛", "整數間隙"],
  },
  {
    subject: "algo",
    groupSlug: "greedy-algorithms",
    groupName: "Greedy algorithms",
    slug: "greedy-algorithm-general",
    name: "Greedy algorithms (general)",
    aliases: ["貪婪演算法", "貪婪法", "交換論證", "活動選擇", "區間排程"],
  },
  {
    subject: "algo",
    groupSlug: "randomized-algorithms",
    groupName: "Randomized algorithms",
    slug: "randomized-algorithm",
    name: "Randomized algorithms",
    aliases: [
      "隨機演算法",
      "隨機化演算法",
      "隨機排列",
      "Fisher-Yates洗牌",
      "隨機選擇",
      "期望值分析",
      "均勻分布",
    ],
  },
  {
    subject: "algo",
    groupSlug: "heap-and-priority-queue",
    groupName: "Heap and priority queue",
    slug: "binary-heap",
    name: "Binary heap",
    aliases: [
      "二元堆積",
      "二元最小堆積",
      "上浮",
      "下沉heapify",
      "堆積建構",
      "BUILD-MAX-HEAP",
      "最小堆積",
      "陣列表示",
    ],
  },

  // algo also tags classic DS questions (this corpus tags ds vs algo per-question, not
  // per-paper); mirrors ds's structural groups above with its own rows (subject-scoped).
  {
    subject: "algo",
    groupSlug: "linear-structures",
    groupName: "Linear structures",
    slug: "stack",
    name: "Stack",
    aliases: ["堆疊", "LIFO", "陣列實作", "復原操作"],
  },
  {
    subject: "algo",
    groupSlug: "linear-structures",
    groupName: "Linear structures",
    slug: "queue",
    name: "Queue",
    aliases: ["環狀佇列", "滿判斷", "模運算"],
  },
  {
    subject: "algo",
    groupSlug: "linear-structures",
    groupName: "Linear structures",
    slug: "linked-list",
    name: "Linked list",
    aliases: ["鏈結串列", "雙向鏈結串列", "走訪方向"],
  },
  {
    subject: "algo",
    groupSlug: "trees",
    groupName: "Trees",
    slug: "binary-search-tree",
    name: "Binary search tree",
    aliases: [
      "二元搜尋樹",
      "平衡樹",
      "根節點",
      "搜尋深度",
      "節點刪除",
      "中序後繼",
      "前序走訪",
      "後序走訪",
      "AVL旋轉",
    ],
  },
  {
    subject: "algo",
    groupSlug: "trees",
    groupName: "Trees",
    slug: "red-black-tree",
    name: "Red-black tree",
    // "重新著色" excluded — ambiguous, also appears in an unrelated tree-DP/vertex-cover
    // question (ntu/2025/dsa/q15.md) and would false-positive-tag it here.
    aliases: ["紅黑樹", "旋轉", "性質修復", "旋轉維護", "順序統計樹", "子樹大小"],
  },
  {
    subject: "algo",
    groupSlug: "trees",
    groupName: "Trees",
    slug: "b-tree",
    name: "B-tree",
    aliases: ["B樹", "節點分裂", "內部節點刪除", "前驅後繼替換", "最小度數"],
  },
  {
    subject: "algo",
    groupSlug: "hashing",
    groupName: "Hashing",
    slug: "hash-table",
    name: "Hash table",
    aliases: [
      "雜湊表",
      "開放定址",
      "線性探測",
      "雙重雜湊",
      "負載因子",
      "分離鏈結",
      "動態擴容",
      "探測序列",
      "最大公因數",
    ],
  },
  {
    subject: "algo",
    groupSlug: "disjoint-set",
    groupName: "Disjoint set (union-find)",
    slug: "disjoint-set-union",
    name: "Disjoint set union (union-find)",
    aliases: ["併查集", "並查集", "互斥集合", "加權聯集", "鏈結串列表示"],
  },
  {
    subject: "algo",
    groupSlug: "recursion",
    groupName: "Recursion",
    slug: "recursion-call-stack",
    name: "Recursion and the call stack",
    aliases: ["遞迴追蹤", "堆疊溢位"],
  },
  {
    subject: "algo",
    groupSlug: "polynomial-evaluation",
    groupName: "Polynomial evaluation",
    slug: "horners-rule",
    name: "Horner's rule",
    aliases: ["Horner法則", "多項式求值", "迴圈不變式"],
  },

  // ---------- english (英文) ----------
  // Excludes format labels (克漏字/語境填空/篇章理解/閱讀理解) and article-topic tags
  // (AI論述/學術論述/政策變革/etc.) — neither is a testable English-skill concept.
  {
    subject: "english",
    groupSlug: "vocabulary",
    groupName: "Vocabulary",
    slug: "vocabulary-in-context",
    name: "Vocabulary in context",
    aliases: ["詞彙", "學術詞彙", "政治詞彙"],
  },
  {
    subject: "english",
    groupSlug: "vocabulary",
    groupName: "Vocabulary",
    slug: "word-discrimination",
    name: "Word discrimination",
    aliases: [
      "動詞辨析",
      "名詞辨析",
      "形容詞辨析",
      "詞性",
      "名詞動詞化",
      "易混淆字",
      "拼字辨義",
      "近義辨析",
      "近反義辨析",
      "數量名詞",
      "imply與infer辨析",
      "differentiate between",
      "component",
      "emit",
      "myriads of",
    ],
  },
  {
    subject: "english",
    groupSlug: "vocabulary",
    groupName: "Vocabulary",
    slug: "collocations-and-phrases",
    name: "Collocations and phrases",
    aliases: [
      "動詞搭配",
      "形容詞搭配",
      "名詞搭配",
      "慣用語",
      "介系詞片語",
      "片語動詞",
      "abound in",
      "binge on",
      "indigenous to",
      "access to",
      "compare with",
      "carry out",
      "interfere with",
      "by definition",
    ],
  },
  {
    subject: "english",
    groupSlug: "vocabulary",
    groupName: "Vocabulary",
    slug: "word-formation",
    name: "Word formation",
    aliases: ["構詞法", "字首de-"],
  },
  {
    subject: "english",
    groupSlug: "vocabulary",
    groupName: "Vocabulary",
    slug: "contextual-meaning-inference",
    name: "Contextual meaning inference",
    aliases: [
      "語境同義",
      "片語理解",
      "詞義理解",
      "詞義推論",
      "詞義推敲",
      "上下文線索",
      "同義字",
      "字面義與言外之意",
    ],
  },
  {
    subject: "english",
    groupSlug: "grammar",
    groupName: "Grammar",
    slug: "relative-clauses",
    name: "Relative clauses",
    aliases: ["關係代名詞", "數量詞of which", "數量詞加of which或whom", "非限定子句"],
  },
  {
    subject: "english",
    groupSlug: "grammar",
    groupName: "Grammar",
    slug: "tense-and-aspect",
    name: "Tense and aspect",
    aliases: ["時態", "過去簡單式", "未來完成進行式"],
  },
  {
    subject: "english",
    groupSlug: "grammar",
    groupName: "Grammar",
    slug: "subjunctive-mood",
    name: "Subjunctive mood",
    aliases: ["假設語氣", "與過去事實相反", "It is time 句型"],
  },
  {
    subject: "english",
    groupSlug: "grammar",
    groupName: "Grammar",
    slug: "subject-verb-agreement",
    name: "Subject-verb agreement",
    aliases: ["主謂一致", "neither of單數", "neither nor就近原則", "主謂一致與時態"],
  },
  {
    subject: "english",
    groupSlug: "grammar",
    groupName: "Grammar",
    slug: "connectives-and-conjunctions",
    name: "Connectives and conjunctions",
    aliases: ["連接詞", "連接片語", "albeit", "in the sense that"],
  },
  {
    subject: "english",
    groupSlug: "grammar",
    groupName: "Grammar",
    slug: "participial-construction",
    name: "Participial construction",
    aliases: ["分詞構句", "懸垂修飾語"],
  },
  {
    subject: "english",
    groupSlug: "grammar",
    groupName: "Grammar",
    slug: "noun-clauses",
    name: "Noun clauses",
    aliases: ["名詞子句", "to what extent"],
  },
  {
    subject: "english",
    groupSlug: "grammar",
    groupName: "Grammar",
    slug: "infinitives-and-gerunds",
    name: "Infinitives and gerunds",
    aliases: ["不定詞", "動詞原形", "deny doing", "動詞加動名詞", "介系詞to加動名詞"],
  },
  {
    subject: "english",
    groupSlug: "grammar",
    groupName: "Grammar",
    slug: "future-and-modal-constructions",
    name: "Future and modal constructions",
    aliases: ["be to 句型", "未來安排"],
  },
  {
    subject: "english",
    groupSlug: "reading-comprehension",
    groupName: "Reading comprehension",
    slug: "detail-location",
    name: "Detail location",
    aliases: ["細節定位", "細節判讀", "細節推論", "細節比對", "訊息定位", "數據比對", "年代比對"],
  },
  {
    subject: "english",
    groupSlug: "reading-comprehension",
    groupName: "Reading comprehension",
    slug: "main-idea-and-purpose",
    name: "Main idea and purpose",
    aliases: ["主旨大意", "主旨推論", "主旨涵蓋", "主旨脈絡", "篇章目的", "標題主旨", "未涵蓋判斷"],
  },
  {
    subject: "english",
    groupSlug: "reading-comprehension",
    groupName: "Reading comprehension",
    slug: "inference",
    name: "Inference",
    aliases: ["推論", "推論判讀", "反向推論", "隱含概念"],
  },
  {
    subject: "english",
    groupSlug: "reading-comprehension",
    groupName: "Reading comprehension",
    slug: "author-stance-and-conclusion",
    name: "Author's stance and conclusion",
    aliases: ["作者論點", "作者建議", "作者立場", "作者主張", "結論定位", "結論判讀"],
  },
  {
    subject: "english",
    groupSlug: "reading-comprehension",
    groupName: "Reading comprehension",
    slug: "true-false-verification",
    name: "True/false verification",
    aliases: ["是非判斷", "是非判讀", "未提及判斷"],
  },
  {
    subject: "english",
    groupSlug: "reading-comprehension",
    groupName: "Reading comprehension",
    slug: "tone-and-purpose",
    name: "Tone and purpose",
    aliases: ["文體判斷", "語氣與目的", "語氣判斷"],
  },
  {
    subject: "english",
    groupSlug: "reading-comprehension",
    groupName: "Reading comprehension",
    slug: "logical-relationships-in-text",
    name: "Logical relationships in text",
    aliases: [
      "因果關係",
      "因果邏輯",
      "因果線索",
      "因果推論",
      "概念連結",
      "概念對比",
      "對比線索",
      "句間關係",
      "句意釋義",
      "讓步結構",
      "讓步與因果",
    ],
  },
  {
    subject: "english",
    groupSlug: "reading-comprehension",
    groupName: "Reading comprehension",
    slug: "argument-evaluation",
    name: "Argument evaluation",
    aliases: ["論證評價", "論證手法", "例證功能"],
  },
];

export interface KnowledgePointSeedResult {
  groups: number;
  leaves: number;
}

// Idempotent per-subject upsert: L1 groups then L2 leaves, then delete leaves no longer listed
// (same reconcile as seedTaxonomy's track_subject; safe since QuestionKnowledgePoint cascades).
export async function seedKnowledgePoints(prisma: PrismaClient): Promise<KnowledgePointSeedResult> {
  const bySubject = new Map<string, KnowledgePointSeed[]>();
  for (const entry of KNOWLEDGE_POINTS) {
    const list = bySubject.get(entry.subject) ?? [];
    list.push(entry);
    bySubject.set(entry.subject, list);
  }

  let groups = 0;
  let leaves = 0;

  for (const [subjectSlug, entries] of bySubject) {
    const subject = await prisma.subject.findUnique({
      where: { slug: subjectSlug },
      select: { id: true },
    });
    if (!subject) {
      throw new Error(`unknown subject slug in knowledge-points.seed: "${subjectSlug}"`);
    }

    const groupIdBySlug = new Map<string, string>();
    const wantedSlugs = new Set<string>();

    for (const entry of entries) {
      let groupId = groupIdBySlug.get(entry.groupSlug);
      if (!groupId) {
        // Reset parentId on update too, in case this slug was once a colliding leaf.
        const groupRow = await prisma.knowledgePoint.upsert({
          where: { subjectId_slug: { subjectId: subject.id, slug: entry.groupSlug } },
          update: { name: entry.groupName, parentId: null },
          create: { subjectId: subject.id, slug: entry.groupSlug, name: entry.groupName },
        });
        groupId = groupRow.id;
        groupIdBySlug.set(entry.groupSlug, groupId);
        wantedSlugs.add(entry.groupSlug);
        groups += 1;
      }

      await prisma.knowledgePoint.upsert({
        where: { subjectId_slug: { subjectId: subject.id, slug: entry.slug } },
        update: { name: entry.name, aliases: entry.aliases ?? [], parentId: groupId },
        create: {
          subjectId: subject.id,
          slug: entry.slug,
          name: entry.name,
          aliases: entry.aliases ?? [],
          parentId: groupId,
        },
      });
      wantedSlugs.add(entry.slug);
      leaves += 1;
    }

    await prisma.knowledgePoint.deleteMany({
      where: { subjectId: subject.id, slug: { notIn: [...wantedSlugs] } },
    });
  }

  return { groups, leaves };
}
